import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { antonio } from "./fonts";

export const metadata: Metadata = {
  title: "The Planets Fact",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx([antonio.variable, "font-sans"])}>{children}</body>
    </html>
  );
}
